### ISSUE TITLE
Invalid parameter group_create

### ISSUE THREAD

**Issue by PHaroZ** [dj-wasabi/puppet-zabbix#100] opened 2015-06-10 07:27 UTC
Hi,

With the new 1.5.0 version I've this error message :
```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid parameter group_create on Zabbix_host[zabbix0.lan.xxxx] at /etc/puppet/modules/zabbix/manifests/resources/agent.pp:27 on node zabbix0.lan.xxxx
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```
To temporarily avoid this I've to comment /etc/puppet/modules/zabbix/manifests/resources/agent.pp:32.

I've never wrote any puppet type but as far as I can see ./lib/puppet/provider/zabbix_host/ruby.rb and ./lib/puppet/type/zabbix_host.rb seems to be ok with this new feature ...

**Comment by dj-wasabi** [comment] 2015-08-20 09:07
Hi,

How did you configure you site manifest file?

With this example, it works for me:
```
  class { '::zabbix::agent':
    server               => 'wdpuppet06.dj-wasabi.local',
    zabbix_package_state => 'latest',
    zabbix_version       => '2.4',
    manage_resources     => true,
    zbx_group            => 'Pizza',
    zbx_group_create     => true,
  }
```

**Comment by PHaroZ** [comment] 2015-08-24 06:38
Hi,

I do that
``` 
class profiles::zabbix::repo (
  $version = $profiles::zabbix::params::version,
  $zabbix_version = $profiles::zabbix::params::zabbix_version,
) inherits profiles::zabbix::params {
  apt::source { 'zabbix_official':
    location	=> "http://repo.zabbix.com/zabbix/$zabbix_version/debian/",
    release	=> 'wheezy',
    repos	=> 'main',
    key		=> 'FBABD5FB20255ECAB22EE194D13D58E479EA5ED4',
    key_content	=> file('profiles/zabbix-official-repo.key'),
#    key_server	=> 'repo.zabbix.com',
  }
}

class profiles::zabbix::agent (
  $oob_cidr = $profiles::zabbix::params::oob_cidr,
  $server = $profiles::zabbix::params::server,
  $zabbix_version = $profiles::zabbix::params::zabbix_version,
  $zabbix_templateMain,
  $zabbix_templateAdds,
) inherits profiles::zabbix::params {
  class {'::profiles::zabbix::repo':
    stage	=> 'first',
  }

  class {'::zabbix::agent':
    manage_repo	      => false,
    zabbix_version    => $zabbix_version,
    listenip	        => ip_for_network($oob_cidr),
    hostname	        => $::fqdn,
#    hostname	        => ip_for_network($oob_cidr),
    server	          => $server,
    serveractive      => $server,
    manage_resources  => true,
    zbx_templates     => concat([$zabbix_templateMain], $zabbix_templateAdds),
  }

}
```
with : 
$zabbix_version = 2.4
$oob_cidr = 10.128.0.0/9
$server = zabbix0.lan.xxxx

**Comment by elricsfate** [comment] 2015-08-27 19:45
@PHaroZ 

I just recently experienced a similar issue and it was caused by having multiple versions of the module (in different environments) and having cached copies of the older versions on the master. 

Try to restart your Puppet master and rerun to see if that solves your issue.

**Comment by dj-wasabi** [comment] 2015-12-21 18:53
Possible solution provided by @elricsfate. Will close this issue. @PHaroZ if you still encounter problem, please reopen this issue or create a new one.

**Closed by dj-wasabi** 2015-12-21 18:53 UTC
